{
 "title": "Cohort platform-core-services Alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Core-Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "core-services pod restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{app_kubernetes_io_name=\"kube-state-metrics\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"metrics-server\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"grafana-agent-logs\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"grafana-agent-traces\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(kube_pod_container_status_restarts_total{container=\"prometheus-server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Monitoring Agents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Prometheus Monitor Instances Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"prometheus-server\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Grafana Log Agent Instances Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"grafana-agent-logs\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Grafana Traces Agent Instances Running",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"grafana-agent-traces\"})",
     "legendFormat": "__auto"
    },
    {}
   ]
  }
 ]
}